name: vn1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyter
  - ipykernel
  - pip
  - pip:
      - statsforecast
